apiVersion: v1
kind: Pod
metadata: 
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: supersecret
            key: username
            optional: false # same as default; "supersecret" must exist
                            # and include a key named "username"
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: supersecret
            key: password
            optional: false # same as default; "supersecret" must exist
                            # and include a key named "username"
  restartPolicy: Never