Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-01816d07b1128cd2d
      Tags:
        - Key: "Name"
          Value: !Join 
            - " "
            - - "My Instance in"
              - !Ref AWS::Region