---
- name: Webserver setup
  hosts: webservers
  become: yes
  tasks:
    - name: Install httpd
      ansible.builtin.yum:
        name: httpd
        state: present
    
    - name: Start httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

- name: DBserver setup
  hosts: dbservers
  become: yes
  tasks:
    - name: Install mariadb-server
      ansible.builtin.yum:
        name: httpd
        state: present
    
    - name: Start MariaDB Service
      ansible.builtin.service:
        name: mariadb.service
        state: started
        enabled: yes
