---
- name: Provisioning servers
  hosts: all
  become: yes
  roles:
    - shaneholloman.java
    - role: post-install
      vars:
        ntp0: 0.africa.pool.ntp.org
        ntp1: 1.africa.pool.ntp.org
        ntp2: 2.africa.pool.ntp.org
        ntp3: 3.africa.pool.ntp.org
